contentType: Card
title: Cloud Files
name: cloud-files-v3
CollectionModeField:
  CollectionMode: 0
MaxItemsField:
  MaxItems: 3
PriorityField:
  Priority: 5
StreamSource: null
CardComponent: cloud-files-v3/cloud-files-v3-card
StoreMetadataField:
  description: 
  logourl: 
  storehide: !!bool false
  disableWorkplace: !!bool false
  promotion: !!bool false
  disableBriefing: !!bool true
CommonPart:
  Owner: !!int 2
  Container: null
  CreatedUtc: 2020-03-17T10:19:31.4406019Z
  PublishedUtc: 2020-03-17T10:25:58.0632880Z
  ModifiedUtc: 2020-03-17T10:25:57.9883266Z
  VersionCreatedUtc: 2020-03-17T10:25:57.0000000
  VersionPublishedUtc: 2020-03-17T10:25:58.0000000
  VersionModifiedUtc: 2020-03-17T10:25:57.0000000
ServicePart:
  ConnectorTypeName: ScriptConnector
  ConnectorTypeId: !!int 15
  ConnectorName: ms-graph
  ServiceName: documents-aggregated
  Url: ~/api/adenin.GateKeeper.Connector/ms-graph/documents-aggregated
  ServiceParameters: '{}'
SearchContextPart:
  Query: null
  Interface: null
CommandPart:
  CommandType: None
  Command: 
  DefaultDate: null
  Intent: null
  Ext: {}
AppPart:
  App: null
  Url: 
  ExtUrl: 
  Priority: !!int 0
  AppFaceId: !!int 0
  Category: orange
  Icon: now:search
  CSSClasses: null
  Enabled: !!bool false
  NewWindow: !!bool false
  UrlWithId: !!bool true
  AvailableAppFaceRecords: null
  HasPattern: !!bool false
RoleViewPermissionsPart:
  AllowedRoles: []
  Audiences:
    - Authenticated
  Mandatory: False
RecurringTaskPart:
  Schedule: '- - - - -'
  ActivityType: adenin.Now.Activities.CardTask.UpdateCard
  StartDateUtc: null
  EndDateUtc: null
  NextOccurrenceUtc: null
  Priority: !!int 5
  Status: Enabled
  NowFlag: 0
  LastExecutionUTC: null
  EnableWebHook: !!bool false
  WebHookToken: null
